- name: Install packages (Debian based)
  apt:
    name: wget
    state: latest
  when: ansible_os_family == "Debian"
- name: Install packages (CentOS based)
  yum:
    name: wget
    state: latest
    when: ansible_os_family == "Centos"
  tags: essential-package
- name: Installing Packer tool
  unarchive:
    src: https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
  tags: binary-packer
- name: Installing Vault tool
  unarchive:
    src: https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
  tags: binary-vault
- name: Installing Terraform tool
  unarchive:
    src: https://releases.hashicorp.com/terraform/terraform_0.12.24
    dest: /usr/bin
    remote_src: yes
  tags: binary-terraform
- name: Installing Consul tool
  unarchive:
    src: https://releases.hashicorp.com/consul/consul_1.7.2
    dest: /usr/bin
    remote_src: yes
  tags: binary-consul
- name: Installing Vagrant tool
  unarchive:
    src: https://releases.hashicorp.com/vagrant/vagrant_2.2.7
    dest: /usr/bin
    remote_src: yes
  tags: binary-vagrant
- name: Installing Nomad tool
  unarchive:
    src: https://releases.hashicorp.com/nomad/nomad_0.11.0
    dest: /usr/bin
    remote_src: yes
  tags: binary-nomad

