---
- hosts: local
  tasks:
    - name: Preparing system for updating
      apt:
        update_cache: yes
        upgrade: yes
    - name: Remove useless packages from the cache
      apt: 
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

...