- hosts: local
  become: yes
  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Starting nginx
      service: 
        name: nginx
        state: started
    - name: Copying the index file for remote machine
      template:
        src: index.html
        dest: /var/www/html/index.html
    - name: Copying nginx service
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restarting nginx
      handlers:
      - name: restarting nginx
        service:
          name: nginx
          state: restarted