---
- hosts: local
  tasks:
    - name: Installing some Linux commands
      apt: name={{ item }} state=present
      with_items:
        - vim
        - git
        - nmap
        - net-tools
        - sysstat
        - iptraf
        - cockpit
        - tcpdump
        - virtualbox
        - wireshark
        - python3
        - curl
    - name: Installing another tools
      apt: 
...