---
- hosts: local
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        update_cache: yes
        upgrade: yes
      tags: updating
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      tags: remove packages
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      tags: remove dependencies
...